import type { Metadata } from "next";
import { Inter, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/components/NavBar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const dmSerif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-dm-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerif.variable} ${inter.variable} antialiased min-h-screen flex flex-col`}
      >
        <header className="absolute top-0 left-0 w-full z-50 shadow-md">
          <NavBar />
        </header>
        <main className="flex-grow">{children}</main>
        <footer className="flex justify-center bg-red-700 py-9 mt-16 px-4">
          <span>Copyright © 2025 BushidoBites. All rights reserved</span>
        </footer>
      </body>
    </html>
  );
}
